/**
 * 
 */
package com.uns.importer;

import java.util.Hashtable;

import org.compiere.model.PO;

/**
 * @author Haryadi
 *
 */
public interface ImporterValidation {

	/**
	 * Validate before saving a PO.
	 * @param po
	 * @param freeColVals TODO
	 * @return String of message if error occurs, null if succeed.
	 */
	public String beforeSave (Hashtable<String, PO> poRefMap, PO po, Hashtable<String, Object> freeColVals, int currentRow);
	
	/**
	 * Validate after saving a row of PO.
	 * @param po
	 * @param freeColVals TODO
	 * @return String of message if error occurs, null if succeed.
	 */
	public String afterSaveRow (Hashtable<String, PO> poRefMap, PO po, Hashtable<String, Object> freeColVals, int currentRow);
	
	/**
	 * Validate after saving all row of imported POs.
	 * @param po
	 * @return String of message if error occurs, null if succeed.
	 */
	public String afterSaveAllRow (Hashtable<String, PO> poRefMap, PO[] pos);
	
	/**
	 * Get the PO reference Map which is generated by this ImportValidation Instance.
	 * @return
	 */
	public Hashtable<String, PO> getPOReferenceMap();
	
	/**
	 * 
	 * @param trxName
	 */
	public void setTrxName(String trxName);
}
